<!--[if !IE]>-->
<object classid="java:Sample2.class" 
        type="application/x-java-applet"
        archive="Sample2.jar" 
        height="300" width="550" >
<!-- Konqueror browser needs the following param -->
<param name="archive" value="Sample2.jar" />
<!--<![endif]-->
<object classid="clsid:8AD9C840-044E-11D1-B3E9-00805F499D93" 
        height="300" width="550" > 
    <param name="code" value="Sample2" />
    <param name="archive" value="Sample2.jar" />
</object> 
<!--[if !IE]>-->
</object>
<!--<![endif]-->