<?php
$this->form->setAction($this->url());
echo $this->form;
?>

<h3>Information about the confidentiality of the inserted data</h3>
<p>
    <strong>(*)</strong> These elements are required inputs<br/>
    <strong>(°)</strong> Adding an email address is optional, but required for some
    features like automatically forwarding mails to your standard email address
</p>
<p>
    Each of the features you inserted into the above form,
    <strong>
        except for your email address and, if you gave us your real name,
        your user name
    </strong>
    , will be visible for certain others at your profile page.
</p>

<h4>Why should I insert additional optional data?</h4>
<p>
    Giving others additional information about your identity will make it easier
    for people knowing you to be sure about your identity when visiting your profile.
    Thus, by acknowledging knowing you, they will help you increase your integrity
    score.
</p>